# Generated by Django 4.1.5 on 2023-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_post_options_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
